import type { GraphDocument } from "../../server/api/routers/kg";

export const EXAMPLE_GRAPH_DOCUMENT: GraphDocument = {
  nodes: [
    {
      id: 0,
      name: "国立西洋美術館",
      label: "Museum",
      properties: { name: "国立西洋美術館" },
    },
    {
      id: 1,
      name: "田中功起",
      label: "Artist",
      properties: { name: "田中功起" },
    },
    { id: 2, name: "新藤淳", label: "Curator", properties: { name: "新藤淳" } },
    {
      id: 3,
      name: "飯山由貴",
      label: "Artist",
      properties: { name: "飯山由貴" },
    },
    {
      id: 4,
      name: "遠藤麻衣",
      label: "Artist",
      properties: { name: "遠藤麻衣" },
    },
    {
      id: 5,
      name: "鷹野隆大",
      label: "Artist",
      properties: { name: "鷹野隆大" },
    },
    {
      id: 6,
      name: "長島有里枝",
      label: "Artist",
      properties: { name: "長島有里枝" },
    },
    {
      id: 7,
      name: "ミヤギフトシ",
      label: "Artist",
      properties: { name: "ミヤギフトシ" },
    },
    {
      id: 8,
      name: "梅津庸一",
      label: "Artist",
      properties: { name: "梅津庸一" },
    },
    { id: 9, name: "杉戸洋", label: "Artist", properties: { name: "杉戸洋" } },
    {
      id: 10,
      name: "弓指寛治",
      label: "Artist",
      properties: { name: "弓指寛治" },
    },
    {
      id: 11,
      name: "松浦寿夫",
      label: "Artist",
      properties: { name: "松浦寿夫" },
    },
    { id: 12, name: "小沢剛", label: "Artist", properties: { name: "小沢剛" } },
    {
      id: 13,
      name: "小田原のどか",
      label: "Artist",
      properties: { name: "小田原のどか" },
    },
    {
      id: 14,
      name: "田中功起",
      label: "Artist",
      properties: { name: "田中功起" },
    },
    {
      id: 15,
      name: "山本浩貴",
      label: "Researcher",
      properties: { name: "山本浩貴" },
    },
  ],
  relationships: [
    {
      id: 0,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "田中功起",
      targetId: 1,
      properties: {},
    },
    {
      id: 1,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "新藤淳",
      targetId: 2,
      properties: {},
    },
    {
      id: 2,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "飯山由貴",
      targetId: 3,
      properties: {},
    },
    {
      id: 3,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "遠藤麻衣",
      targetId: 4,
      properties: {},
    },
    {
      id: 4,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "鷹野隆大",
      targetId: 5,
      properties: {},
    },
    {
      id: 5,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "長島有里枝",
      targetId: 6,
      properties: {},
    },
    {
      id: 6,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "ミヤギフトシ",
      targetId: 7,
      properties: {},
    },
    {
      id: 7,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "梅津庸一",
      targetId: 8,
      properties: {},
    },
    {
      id: 8,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "杉戸洋",
      targetId: 9,
      properties: {},
    },
    {
      id: 9,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "弓指寛治",
      targetId: 10,
      properties: {},
    },
    {
      id: 10,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "松浦寿夫",
      targetId: 11,
      properties: {},
    },
    {
      id: 11,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "小沢剛",
      targetId: 12,
      properties: {},
    },
    {
      id: 12,
      sourceName: "国立西洋美術館",
      sourceId: 0,
      type: "hosts",
      targetName: "小田原のどか",
      targetId: 13,
      properties: {},
    },
    {
      id: 13,
      sourceName: "田中功起",
      sourceId: 1,
      type: "proposes",
      targetName: "新藤淳",
      targetId: 2,
      properties: {},
    },
  ],
};
